// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  auto: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
